name: CD

on:
  push:
    tags: [ v* ]
  workflow_dispatch:

jobs:
  build_and_release:
    runs-on: ubuntu-20.04
    name: Build and Release Binaries
    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v5

      # Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: 1.24

      # Create dist directory
      - name: Create dist directory
        run: mkdir -p dist

      # Write the tag version to a the cmd/version.txt file
      - name: Write version to file
        if: github.event_name != 'workflow_dispatch'
        run: echo "${{ github.ref_name }}" > cmd/version.txt

      # Build for ARMv6
      - name: Build for ARMv6
        run: |
          GOOS=linux GOARCH=arm GOARM=6 go build -o dist/frame-light-armv6 cmd/main.go

      # Build for ARMv7
      - name: Build for ARMv7
        run: |
          GOOS=linux GOARCH=arm GOARM=7 go build -o dist/frame-light-armv7 cmd/main.go

      # Create a release and upload binaries
      - name: Create Release and Upload Binaries
        uses: softprops/action-gh-release@v2.4.0
        if: github.event_name != 'workflow_dispatch'
        with:
          files: |
            dist/frame-light-armv6
            dist/frame-light-armv7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      # For workflow_dispatch, upload the binaries in the dist/ folder as artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        if: github.event_name == 'workflow_dispatch'
        with:
          name: binaries
          path: dist/

